#!/bin/bash

SHA=`git rev-parse --short HEAD`


# Get current branch
current_branch="$(git name-rev --name-only HEAD)"
echo $current_branch

if [ "$current_branch" == "master" ]
then
  # Create a tag for that commit number to use for tracking but also update latest
  docker build -t earthlab/earth-analytics-python-env:$SHA .
  docker build -t earthlab/earth-analytics-python-env:latest .
else
  # Create a tag for that particular branch
  docker build -t earthlab/earth-analytics-python-env:$current_branch .
fi
